module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx,mdx}",
    "./gatsby-browser.js",
    "./gatsby-ssr.js",
  ],
  darkMode: "class",
  safelist: [
    // Custom classes
    "headline",
    "secondary-h",
    "sub-h",
    "article",
    "link-default",
    "recent-publications",
    // Layout classes
    "container",
    "mx-auto",
    "px-4",
    "py-6",
    "py-16",
    "px-6",
    "pl-9",
    "pr-10",
    "grid",
    "grid-cols-1",
    "md:grid-cols-12",
    "col-span-3",
    "col-span-9",
    "bg-white",
    "dark:bg-gray-800",
    "shadow-lg",
    "border-r",
    "dark:border-gray-700",
    "pt-12",
    "pt-5",
    "sticky",
    "top-0",
    // Typography classes
    "text-gray-500",
    "dark:text-gray-400",
    "text-gray-700",
    "dark:text-gray-300",
    "text-gray-900",
    "dark:text-white",
    "text-yellow-600",
    "dark:text-yellow-400",
    "hover:text-gray-600",
    "dark:hover:text-gray-300",
    "leading-5",
    "leading-8",
    "leading-9",
    "tracking-tight",
    // Spacing classes
    "mt-3",
    "mt-4",
    "mb-3",
    "p-6",
    // List classes
    "list-disc",
    "list-decimal",
    "ml-6",
    // Table classes
    "border-separate",
    "border-collapse",
    "table-fixed",
    "border",
    "border-yellow-400",
    "dark:border-yellow-600",
    "border-yellow-300",
    "dark:border-yellow-700",
    "bg-yellow-100",
    "dark:bg-yellow-900",
    "text-left",
    "px-3",
    "py-1.5",
    "w-1/2",
    // Theme toggle classes
    "bg-gray-200",
    "dark:bg-gray-700",
    "text-gray-800",
    "dark:text-gray-200",
    "hover:bg-gray-300",
    "dark:hover:bg-gray-600",
    // Sidebar controls
    "fixed",
    "inset-0",
    "z-40",
    "z-50",
    "bg-black",
    "bg-opacity-50",
    "hidden",
    "flex",
    "items-center",
    "justify-between",
    "mb-4",
    "pb-2",
    "border-b",
    "border-gray-200",
    "dark:border-gray-700",
    "transition-all",
    "duration-300",
    "overflow-y-auto",
    "w-6",
    "h-6",
    "p-3",
    "rounded-lg",
    "md:hidden",
    "md:col-span-1",
    "md:col-span-11",
    "col-span-1",
    "col-span-11",
    "justify-center",
    "justify-between",
    "items-center",
    "text-xl",
    "font-semibold",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
